"""added user_technology_stack tablцйуe

Revision ID: 02484d8bb550
Revises: 9907055489c4
Create Date: 2025-04-06 20:30:33.580595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02484d8bb550'
down_revision: Union[str, None] = '9907055489c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_technology_stack',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_technology_stack', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_technology_stack'], ['technology_stack.id_technology_stack'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_technology_stack')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_technology_stack')
    # ### end Alembic commands ###
