"""create user table

Revision ID: 1798bedfd0fb
Revises: 1ff8cf4f0cc4
Create Date: 2025-04-28 16:47:32.552179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1798bedfd0fb'
down_revision: Union[str, None] = '1ff8cf4f0cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
