"""Add user_technology_stack table

Revision ID: 1ff8cf4f0cc4
Revises: 02484d8bb550
Create Date: 2025-04-06 20:34:31.873024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff8cf4f0cc4'
down_revision: Union[str, None] = '02484d8bb550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
