"""init

Revision ID: 31f014d6102e
Revises: 
Create Date: 2025-04-04 16:37:21.948749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f014d6102e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id_organizations', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('domein', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_organizations')
    )
    op.create_index(op.f('ix_organization_id_organizations'), 'organization', ['id_organizations'], unique=False)
    op.create_table('role_organization',
    sa.Column('id_role_organization', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_role_organization')
    )
    op.create_index(op.f('ix_role_organization_id_role_organization'), 'role_organization', ['id_role_organization'], unique=False)
    op.create_table('role_project',
    sa.Column('id_role_project', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_role_project')
    )
    op.create_index(op.f('ix_role_project_id_role_project'), 'role_project', ['id_role_project'], unique=False)
    op.create_table('technology_stack',
    sa.Column('id_technology_stack', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_technology_stack')
    )
    op.create_index(op.f('ix_technology_stack_id_technology_stack'), 'technology_stack', ['id_technology_stack'], unique=False)
    op.create_table('project',
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('id_organizations', sa.Integer(), nullable=True),
    sa.Column('id_technology_stack', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_organizations'], ['organization.id_organizations'], ),
    sa.ForeignKeyConstraint(['id_technology_stack'], ['technology_stack.id_technology_stack'], ),
    sa.PrimaryKeyConstraint('id_project')
    )
    op.create_index(op.f('ix_project_id_project'), 'project', ['id_project'], unique=False)
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('img', sa.String(length=50), nullable=True),
    sa.Column('id_technology_stack', sa.Integer(), nullable=True),
    sa.Column('is_looking_for_project', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_technology_stack'], ['technology_stack.id_technology_stack'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id_user'), 'user', ['id_user'], unique=False)
    op.create_table('user_organization',
    sa.Column('id_user_organization', sa.Integer(), nullable=False),
    sa.Column('id_role_organization', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_organizations', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_organizations'], ['organization.id_organizations'], ),
    sa.ForeignKeyConstraint(['id_role_organization'], ['role_organization.id_role_organization'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user_organization')
    )
    op.create_index(op.f('ix_user_organization_id_user_organization'), 'user_organization', ['id_user_organization'], unique=False)
    op.create_table('user_project',
    sa.Column('id_user_project', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.Column('id_role_project', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_project'], ['project.id_project'], ),
    sa.ForeignKeyConstraint(['id_role_project'], ['role_project.id_role_project'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user_project')
    )
    op.create_index(op.f('ix_user_project_id_user_project'), 'user_project', ['id_user_project'], unique=False)
    op.create_table('user_project_history',
    sa.Column('id_user_project_history', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.Column('id_organizations', sa.Integer(), nullable=True),
    sa.Column('id_role_project', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_organizations'], ['organization.id_organizations'], ),
    sa.ForeignKeyConstraint(['id_project'], ['project.id_project'], ),
    sa.ForeignKeyConstraint(['id_role_project'], ['role_project.id_role_project'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user_project_history')
    )
    op.create_index(op.f('ix_user_project_history_id_user_project_history'), 'user_project_history', ['id_user_project_history'], unique=False)
    op.create_table('vacancy',
    sa.Column('id_vacancy', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id_role_project', sa.Integer(), nullable=True),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_project'], ['project.id_project'], ),
    sa.ForeignKeyConstraint(['id_role_project'], ['role_project.id_role_project'], ),
    sa.PrimaryKeyConstraint('id_vacancy')
    )
    op.create_index(op.f('ix_vacancy_id_vacancy'), 'vacancy', ['id_vacancy'], unique=False)
    op.create_table('vacancy_responses',
    sa.Column('id_vacancy_responses', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id_vacancy', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.ForeignKeyConstraint(['id_vacancy'], ['vacancy.id_vacancy'], ),
    sa.PrimaryKeyConstraint('id_vacancy_responses')
    )
    op.create_index(op.f('ix_vacancy_responses_id_vacancy_responses'), 'vacancy_responses', ['id_vacancy_responses'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_responses_id_vacancy_responses'), table_name='vacancy_responses')
    op.drop_table('vacancy_responses')
    op.drop_index(op.f('ix_vacancy_id_vacancy'), table_name='vacancy')
    op.drop_table('vacancy')
    op.drop_index(op.f('ix_user_project_history_id_user_project_history'), table_name='user_project_history')
    op.drop_table('user_project_history')
    op.drop_index(op.f('ix_user_project_id_user_project'), table_name='user_project')
    op.drop_table('user_project')
    op.drop_index(op.f('ix_user_organization_id_user_organization'), table_name='user_organization')
    op.drop_table('user_organization')
    op.drop_index(op.f('ix_user_id_user'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_project_id_project'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_technology_stack_id_technology_stack'), table_name='technology_stack')
    op.drop_table('technology_stack')
    op.drop_index(op.f('ix_role_project_id_role_project'), table_name='role_project')
    op.drop_table('role_project')
    op.drop_index(op.f('ix_role_organization_id_role_organization'), table_name='role_organization')
    op.drop_table('role_organization')
    op.drop_index(op.f('ix_organization_id_organizations'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
