"""Auto migration

Revision ID: 71b36fcc6beb
Revises: c06a6e7d1741
Create Date: 2025-05-28 15:09:11.810663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b36fcc6beb'
down_revision: Union[str, None] = 'c06a6e7d1741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_organization',
    sa.Column('id_invite', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('id_organizations', sa.Integer(), nullable=True),
    sa.Column('id_role_organization', sa.Integer(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_organizations'], ['organization.id_organizations'], ),
    sa.ForeignKeyConstraint(['id_role_organization'], ['role_organization.id_role_organization'], ),
    sa.PrimaryKeyConstraint('id_invite')
    )
    op.create_index(op.f('ix_invite_organization_email'), 'invite_organization', ['email'], unique=False)
    op.create_index(op.f('ix_invite_organization_id_invite'), 'invite_organization', ['id_invite'], unique=False)
    op.create_index(op.f('ix_invite_organization_token'), 'invite_organization', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_organization_token'), table_name='invite_organization')
    op.drop_index(op.f('ix_invite_organization_id_invite'), table_name='invite_organization')
    op.drop_index(op.f('ix_invite_organization_email'), table_name='invite_organization')
    op.drop_table('invite_organization')
    # ### end Alembic commands ###
