"""added user_technology_stack table

Revision ID: 9907055489c4
Revises: 394e4aecd571
Create Date: 2025-04-06 20:27:56.937618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9907055489c4'
down_revision: Union[str, None] = '394e4aecd571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_id_technology_stack_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'id_technology_stack')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_technology_stack', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_id_technology_stack_fkey', 'user', 'technology_stack', ['id_technology_stack'], ['id_technology_stack'])
    # ### end Alembic commands ###
