"""Auto migration

Revision ID: a78ea431d86e
Revises: 71b36fcc6beb
Create Date: 2025-06-10 05:54:34.248908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78ea431d86e'
down_revision: Union[str, None] = '71b36fcc6beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'domein',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'organization', ['domein'])
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('project', 'description',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_index(op.f('ix_project_id_project'), table_name='project')
    op.drop_constraint(op.f('user_organization_id_fkey'), 'user', type_='foreignkey')
    op.drop_constraint(op.f('user_role_organization_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'organization_id')
    op.drop_column('user', 'role_organization_id')
    op.drop_index(op.f('ix_user_project_id_user_project'), table_name='user_project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_project_id_user_project'), 'user_project', ['id_user_project'], unique=False)
    op.add_column('user', sa.Column('role_organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_role_organization_id_fkey'), 'user', 'role_organization', ['role_organization_id'], ['id_role_organization'], ondelete='SET NULL')
    op.create_foreign_key(op.f('user_organization_id_fkey'), 'user', 'organization', ['organization_id'], ['id_organizations'], ondelete='SET NULL')
    op.create_index(op.f('ix_project_id_project'), 'project', ['id_project'], unique=False)
    op.alter_column('project', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('project', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'organization', type_='unique')
    op.alter_column('organization', 'domein',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
