"""Auto migration

Revision ID: c06a6e7d1741
Revises: 1798bedfd0fb
Create Date: 2025-04-28 08:42:01.367401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06a6e7d1741'
down_revision: Union[str, None] = '1798bedfd0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('role_organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'role_organization', ['role_organization_id'], ['id_role_organization'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user', 'organization', ['organization_id'], ['id_organizations'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_organization_id')
    op.drop_column('user', 'organization_id')
    # ### end Alembic commands ###
