"""Auto migration

Revision ID: c31f384658a3
Revises: 2d7cb11deaea
Create Date: 2025-06-15 07:29:44.546104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31f384658a3'
down_revision: Union[str, None] = '2d7cb11deaea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('is_remote', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_remote')
    op.drop_column('project', 'is_paid')
    # ### end Alembic commands ###
